export function getPopupElements() {
  return {
    progressEl: document.getElementById("progress"),
    currentTimeEl: document.getElementById("currentTime"),
    durationTimeEl: document.getElementById("durationTime"),
    playBtn: document.getElementById("playBtn"),
    prevBtn: document.getElementById("prevBtn"),
    nextBtn: document.getElementById("nextBtn"),
    modeBtn: document.getElementById("modeBtn"),
    addCurrentBtn: document.getElementById("addCurrentBtn"),
    categorySelect: document.getElementById("categorySelect"),
    manageCategoriesBtn: document.getElementById("manageCategoriesBtn"),
    audioQualitySelect: document.getElementById("audioQualitySelect"),
    categoryManagerDialog: document.getElementById("categoryManagerDialog"),
    categoryManagerList: document.getElementById("categoryManagerList"),
    managerCategoryInput: document.getElementById("managerCategoryInput"),
    managerCategoryConfirmBtn: document.getElementById("managerCategoryConfirmBtn"),
    closeCategoryManagerBtn: document.getElementById("closeCategoryManagerBtn"),
    moveVideoDialog: document.getElementById("moveVideoDialog"),
    moveVideoText: document.getElementById("moveVideoText"),
    moveVideoSelect: document.getElementById("moveVideoSelect"),
    moveVideoHint: document.getElementById("moveVideoHint"),
    confirmMoveVideoBtn: document.getElementById("confirmMoveVideoBtn"),
    cancelMoveVideoBtn: document.getElementById("cancelMoveVideoBtn"),
    deleteConfirmDialog: document.getElementById("deleteConfirmDialog"),
    deleteConfirmText: document.getElementById("deleteConfirmText"),
    confirmDeleteBtn: document.getElementById("confirmDeleteBtn"),
    cancelDeleteBtn: document.getElementById("cancelDeleteBtn"),
    volumeSlider: document.getElementById("volumeSlider"),
    bulkToggle: document.getElementById("bulkSelectToggle"),
    bulkDeleteBtn: document.getElementById("bulkDeleteBtn"),
    importBtn: document.getElementById("importBtn"),
    exportBtn: document.getElementById("exportBtn"),
    importFileInput: document.getElementById("importFileInput"),
    videoListEl: document.getElementById("videoList"),
    feedbackEl: document.getElementById("categoryFeedback")
  };
}
